/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xyz_jvm_example_jni_Test */

#ifndef _Included_org_xyz_jvm_example_jni_Test
#define _Included_org_xyz_jvm_example_jni_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xyz_jvm_example_jni_Test
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xyz_jvm_example_jni_Test_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
